# Generated by Django 3.2.7 on 2022-04-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='EIRcode1',
            field=models.CharField(default='w', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='EIRcode2',
            field=models.CharField(default='w', max_length=20),
            preserve_default=False,
        ),
    ]
