# Generated by Django 3.2.7 on 2022-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20220428_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bags_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
